language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e "create database IF NOT EXISTS sigenes;" -uroot -proot

before_script:
  - npm install -g bower
  - cd sigenes
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - bower install
  - php artisan migrate
  - chmod 777 script.sh
  - sh script.sh
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit